# Generated by Django 3.2.6 on 2021-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
